server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      format-sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        type.descriptor.sql: TRACE
        resource.transaction: DEBUG
        SQL: DEBUG
      springframework:
        transaction.interceptor: TRACE
        jdbc.datasource.DataSourceTransactionManager: DEBUG
        orm.jpa.JpaTransactionManager: DEBUG


#  security:
#    user:
#      name: user
#      password: 1234




eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
