version: '3.9'
services:
  notification:
    container_name: notification
    build: notification
    image: bgpark82/notification
    ports:
      - "8080:8080"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

