server:
  port: 0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-service

logging:
  level:
    org.springframework.cloud.openfeign.FeignLoggerFactory: DEBUG
