###
GET http://localhost:8080/status/health_check

###
GET http://localhost:8080/actuator/health

###
POST http://localhost:8080/actuator/refresh

###
POST http://localhost:8080/actuator/busrefresh

###
GET http://localhost:8080/status/error

