### 아이템을 등록한다
POST http://localhost:8080/items
Content-Type: application/json

{
  "name": "베이비페이스",
  "price": 33000,
  "amount": 100,
  "groups": [
    {
      "name": "필수옵션",
      "options": [
        {
          "name": "일반분석",
          "price": 0,
          "amount": 100
        }
      ]
    },
    {
      "name": "선택옵션",
      "options": [
        {
          "name": "디데이 캘린더",
          "price": 18000,
          "amount": 100
        },
        {
          "name": "포토 스탠드",
          "price": 12000,
          "amount": 100
        }
      ]
    }
  ]
}

### 모든 아이템을 조회한다
GET http://localhost:8080/items
